[package]
name    = "rollbackx-core"
version.workspace = true
edition.workspace = true
authors.workspace = true
license.workspace = true
description = "RollbackX core library — snapshot backends and data types"

[dependencies]
thiserror  = { workspace = true }
anyhow     = { workspace = true }
serde      = { workspace = true }
serde_json = { workspace = true }
chrono     = { workspace = true }
tempfile   = { workspace = true }
